// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: epicurc/auth_api.proto

package epicurc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UrcAuthApi_HealthCheck_FullMethodName                            = "/epic_urc.UrcAuthApi/HealthCheck"
	UrcAuthApi_StartAuthSession_FullMethodName                       = "/epic_urc.UrcAuthApi/StartAuthSession"
	UrcAuthApi_GetAuthSession_FullMethodName                         = "/epic_urc.UrcAuthApi/GetAuthSession"
	UrcAuthApi_RefreshAuthSession_FullMethodName                     = "/epic_urc.UrcAuthApi/RefreshAuthSession"
	UrcAuthApi_VerifyUser_FullMethodName                             = "/epic_urc.UrcAuthApi/VerifyUser"
	UrcAuthApi_ExchangeExternalTokenForUserToken_FullMethodName      = "/epic_urc.UrcAuthApi/ExchangeExternalTokenForUserToken"
	UrcAuthApi_ExchangeAPIKeyForUserToken_FullMethodName             = "/epic_urc.UrcAuthApi/ExchangeAPIKeyForUserToken"
	UrcAuthApi_ExchangeUserTokenForMultiresourceToken_FullMethodName = "/epic_urc.UrcAuthApi/ExchangeUserTokenForMultiresourceToken"
	UrcAuthApi_CheckUserPermission_FullMethodName                    = "/epic_urc.UrcAuthApi/CheckUserPermission"
	UrcAuthApi_LookupUserPermissions_FullMethodName                  = "/epic_urc.UrcAuthApi/LookupUserPermissions"
	UrcAuthApi_GetUserInfo_FullMethodName                            = "/epic_urc.UrcAuthApi/GetUserInfo"
	UrcAuthApi_GetUserId_FullMethodName                              = "/epic_urc.UrcAuthApi/GetUserId"
	UrcAuthApi_GetProviderUserId_FullMethodName                      = "/epic_urc.UrcAuthApi/GetProviderUserId"
)

// UrcAuthApiClient is the client API for UrcAuthApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UrcAuthApiClient interface {
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	StartAuthSession(ctx context.Context, in *StartAuthSessionRequest, opts ...grpc.CallOption) (*StartAuthSessionResponse, error)
	GetAuthSession(ctx context.Context, in *GetAuthSessionRequest, opts ...grpc.CallOption) (*GetAuthSessionResponse, error)
	RefreshAuthSession(ctx context.Context, in *RefreshAuthSessionRequest, opts ...grpc.CallOption) (*RefreshAuthSessionResponse, error)
	VerifyUser(ctx context.Context, in *VerifyUserRequest, opts ...grpc.CallOption) (*VerifyUserResponse, error)
	// For external authentication token login
	ExchangeExternalTokenForUserToken(ctx context.Context, in *ExchangeExternalTokenForUserTokenRequest, opts ...grpc.CallOption) (*ExchangeExternalTokenForUserTokenResponse, error)
	// For API key login
	ExchangeAPIKeyForUserToken(ctx context.Context, in *ExchangeAPIKeyForUserTokenRequest, opts ...grpc.CallOption) (*ExchangeAPIKeyForUserTokenResponse, error)
	// For token exchange
	ExchangeUserTokenForMultiresourceToken(ctx context.Context, in *ExchangeUserTokenForMultiresourceTokenRequest, opts ...grpc.CallOption) (*ExchangeUserTokenForMultiresourceTokenResponse, error)
	// For permission checks
	CheckUserPermission(ctx context.Context, in *CheckUserPermissionRequest, opts ...grpc.CallOption) (*CheckUserPermissionResponse, error)
	LookupUserPermissions(ctx context.Context, in *LookupUserPermissionsRequest, opts ...grpc.CallOption) (*LookupUserPermissionsResponse, error)
	// User metadata
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
	GetUserId(ctx context.Context, in *GetUserIdRequest, opts ...grpc.CallOption) (*GetUserIdResponse, error)
	GetProviderUserId(ctx context.Context, in *GetProviderUserIdRequest, opts ...grpc.CallOption) (*GetProviderUserIdResponse, error)
}

type urcAuthApiClient struct {
	cc grpc.ClientConnInterface
}

func NewUrcAuthApiClient(cc grpc.ClientConnInterface) UrcAuthApiClient {
	return &urcAuthApiClient{cc}
}

func (c *urcAuthApiClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, UrcAuthApi_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urcAuthApiClient) StartAuthSession(ctx context.Context, in *StartAuthSessionRequest, opts ...grpc.CallOption) (*StartAuthSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartAuthSessionResponse)
	err := c.cc.Invoke(ctx, UrcAuthApi_StartAuthSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urcAuthApiClient) GetAuthSession(ctx context.Context, in *GetAuthSessionRequest, opts ...grpc.CallOption) (*GetAuthSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuthSessionResponse)
	err := c.cc.Invoke(ctx, UrcAuthApi_GetAuthSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urcAuthApiClient) RefreshAuthSession(ctx context.Context, in *RefreshAuthSessionRequest, opts ...grpc.CallOption) (*RefreshAuthSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshAuthSessionResponse)
	err := c.cc.Invoke(ctx, UrcAuthApi_RefreshAuthSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urcAuthApiClient) VerifyUser(ctx context.Context, in *VerifyUserRequest, opts ...grpc.CallOption) (*VerifyUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyUserResponse)
	err := c.cc.Invoke(ctx, UrcAuthApi_VerifyUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urcAuthApiClient) ExchangeExternalTokenForUserToken(ctx context.Context, in *ExchangeExternalTokenForUserTokenRequest, opts ...grpc.CallOption) (*ExchangeExternalTokenForUserTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeExternalTokenForUserTokenResponse)
	err := c.cc.Invoke(ctx, UrcAuthApi_ExchangeExternalTokenForUserToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urcAuthApiClient) ExchangeAPIKeyForUserToken(ctx context.Context, in *ExchangeAPIKeyForUserTokenRequest, opts ...grpc.CallOption) (*ExchangeAPIKeyForUserTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeAPIKeyForUserTokenResponse)
	err := c.cc.Invoke(ctx, UrcAuthApi_ExchangeAPIKeyForUserToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urcAuthApiClient) ExchangeUserTokenForMultiresourceToken(ctx context.Context, in *ExchangeUserTokenForMultiresourceTokenRequest, opts ...grpc.CallOption) (*ExchangeUserTokenForMultiresourceTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeUserTokenForMultiresourceTokenResponse)
	err := c.cc.Invoke(ctx, UrcAuthApi_ExchangeUserTokenForMultiresourceToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urcAuthApiClient) CheckUserPermission(ctx context.Context, in *CheckUserPermissionRequest, opts ...grpc.CallOption) (*CheckUserPermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckUserPermissionResponse)
	err := c.cc.Invoke(ctx, UrcAuthApi_CheckUserPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urcAuthApiClient) LookupUserPermissions(ctx context.Context, in *LookupUserPermissionsRequest, opts ...grpc.CallOption) (*LookupUserPermissionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupUserPermissionsResponse)
	err := c.cc.Invoke(ctx, UrcAuthApi_LookupUserPermissions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urcAuthApiClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInfoResponse)
	err := c.cc.Invoke(ctx, UrcAuthApi_GetUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urcAuthApiClient) GetUserId(ctx context.Context, in *GetUserIdRequest, opts ...grpc.CallOption) (*GetUserIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserIdResponse)
	err := c.cc.Invoke(ctx, UrcAuthApi_GetUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *urcAuthApiClient) GetProviderUserId(ctx context.Context, in *GetProviderUserIdRequest, opts ...grpc.CallOption) (*GetProviderUserIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProviderUserIdResponse)
	err := c.cc.Invoke(ctx, UrcAuthApi_GetProviderUserId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UrcAuthApiServer is the server API for UrcAuthApi service.
// All implementations must embed UnimplementedUrcAuthApiServer
// for forward compatibility.
type UrcAuthApiServer interface {
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	StartAuthSession(context.Context, *StartAuthSessionRequest) (*StartAuthSessionResponse, error)
	GetAuthSession(context.Context, *GetAuthSessionRequest) (*GetAuthSessionResponse, error)
	RefreshAuthSession(context.Context, *RefreshAuthSessionRequest) (*RefreshAuthSessionResponse, error)
	VerifyUser(context.Context, *VerifyUserRequest) (*VerifyUserResponse, error)
	// For external authentication token login
	ExchangeExternalTokenForUserToken(context.Context, *ExchangeExternalTokenForUserTokenRequest) (*ExchangeExternalTokenForUserTokenResponse, error)
	// For API key login
	ExchangeAPIKeyForUserToken(context.Context, *ExchangeAPIKeyForUserTokenRequest) (*ExchangeAPIKeyForUserTokenResponse, error)
	// For token exchange
	ExchangeUserTokenForMultiresourceToken(context.Context, *ExchangeUserTokenForMultiresourceTokenRequest) (*ExchangeUserTokenForMultiresourceTokenResponse, error)
	// For permission checks
	CheckUserPermission(context.Context, *CheckUserPermissionRequest) (*CheckUserPermissionResponse, error)
	LookupUserPermissions(context.Context, *LookupUserPermissionsRequest) (*LookupUserPermissionsResponse, error)
	// User metadata
	GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error)
	GetUserId(context.Context, *GetUserIdRequest) (*GetUserIdResponse, error)
	GetProviderUserId(context.Context, *GetProviderUserIdRequest) (*GetProviderUserIdResponse, error)
	mustEmbedUnimplementedUrcAuthApiServer()
}

// UnimplementedUrcAuthApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUrcAuthApiServer struct{}

func (UnimplementedUrcAuthApiServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedUrcAuthApiServer) StartAuthSession(context.Context, *StartAuthSessionRequest) (*StartAuthSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartAuthSession not implemented")
}
func (UnimplementedUrcAuthApiServer) GetAuthSession(context.Context, *GetAuthSessionRequest) (*GetAuthSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuthSession not implemented")
}
func (UnimplementedUrcAuthApiServer) RefreshAuthSession(context.Context, *RefreshAuthSessionRequest) (*RefreshAuthSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshAuthSession not implemented")
}
func (UnimplementedUrcAuthApiServer) VerifyUser(context.Context, *VerifyUserRequest) (*VerifyUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyUser not implemented")
}
func (UnimplementedUrcAuthApiServer) ExchangeExternalTokenForUserToken(context.Context, *ExchangeExternalTokenForUserTokenRequest) (*ExchangeExternalTokenForUserTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeExternalTokenForUserToken not implemented")
}
func (UnimplementedUrcAuthApiServer) ExchangeAPIKeyForUserToken(context.Context, *ExchangeAPIKeyForUserTokenRequest) (*ExchangeAPIKeyForUserTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeAPIKeyForUserToken not implemented")
}
func (UnimplementedUrcAuthApiServer) ExchangeUserTokenForMultiresourceToken(context.Context, *ExchangeUserTokenForMultiresourceTokenRequest) (*ExchangeUserTokenForMultiresourceTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExchangeUserTokenForMultiresourceToken not implemented")
}
func (UnimplementedUrcAuthApiServer) CheckUserPermission(context.Context, *CheckUserPermissionRequest) (*CheckUserPermissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckUserPermission not implemented")
}
func (UnimplementedUrcAuthApiServer) LookupUserPermissions(context.Context, *LookupUserPermissionsRequest) (*LookupUserPermissionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupUserPermissions not implemented")
}
func (UnimplementedUrcAuthApiServer) GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedUrcAuthApiServer) GetUserId(context.Context, *GetUserIdRequest) (*GetUserIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserId not implemented")
}
func (UnimplementedUrcAuthApiServer) GetProviderUserId(context.Context, *GetProviderUserIdRequest) (*GetProviderUserIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProviderUserId not implemented")
}
func (UnimplementedUrcAuthApiServer) mustEmbedUnimplementedUrcAuthApiServer() {}
func (UnimplementedUrcAuthApiServer) testEmbeddedByValue()                    {}

// UnsafeUrcAuthApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UrcAuthApiServer will
// result in compilation errors.
type UnsafeUrcAuthApiServer interface {
	mustEmbedUnimplementedUrcAuthApiServer()
}

func RegisterUrcAuthApiServer(s grpc.ServiceRegistrar, srv UrcAuthApiServer) {
	// If the following call panics, it indicates UnimplementedUrcAuthApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UrcAuthApi_ServiceDesc, srv)
}

func _UrcAuthApi_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrcAuthApiServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrcAuthApi_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrcAuthApiServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrcAuthApi_StartAuthSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartAuthSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrcAuthApiServer).StartAuthSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrcAuthApi_StartAuthSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrcAuthApiServer).StartAuthSession(ctx, req.(*StartAuthSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrcAuthApi_GetAuthSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrcAuthApiServer).GetAuthSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrcAuthApi_GetAuthSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrcAuthApiServer).GetAuthSession(ctx, req.(*GetAuthSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrcAuthApi_RefreshAuthSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshAuthSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrcAuthApiServer).RefreshAuthSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrcAuthApi_RefreshAuthSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrcAuthApiServer).RefreshAuthSession(ctx, req.(*RefreshAuthSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrcAuthApi_VerifyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrcAuthApiServer).VerifyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrcAuthApi_VerifyUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrcAuthApiServer).VerifyUser(ctx, req.(*VerifyUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrcAuthApi_ExchangeExternalTokenForUserToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeExternalTokenForUserTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrcAuthApiServer).ExchangeExternalTokenForUserToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrcAuthApi_ExchangeExternalTokenForUserToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrcAuthApiServer).ExchangeExternalTokenForUserToken(ctx, req.(*ExchangeExternalTokenForUserTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrcAuthApi_ExchangeAPIKeyForUserToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeAPIKeyForUserTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrcAuthApiServer).ExchangeAPIKeyForUserToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrcAuthApi_ExchangeAPIKeyForUserToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrcAuthApiServer).ExchangeAPIKeyForUserToken(ctx, req.(*ExchangeAPIKeyForUserTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrcAuthApi_ExchangeUserTokenForMultiresourceToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExchangeUserTokenForMultiresourceTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrcAuthApiServer).ExchangeUserTokenForMultiresourceToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrcAuthApi_ExchangeUserTokenForMultiresourceToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrcAuthApiServer).ExchangeUserTokenForMultiresourceToken(ctx, req.(*ExchangeUserTokenForMultiresourceTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrcAuthApi_CheckUserPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUserPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrcAuthApiServer).CheckUserPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrcAuthApi_CheckUserPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrcAuthApiServer).CheckUserPermission(ctx, req.(*CheckUserPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrcAuthApi_LookupUserPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupUserPermissionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrcAuthApiServer).LookupUserPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrcAuthApi_LookupUserPermissions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrcAuthApiServer).LookupUserPermissions(ctx, req.(*LookupUserPermissionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrcAuthApi_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrcAuthApiServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrcAuthApi_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrcAuthApiServer).GetUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrcAuthApi_GetUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrcAuthApiServer).GetUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrcAuthApi_GetUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrcAuthApiServer).GetUserId(ctx, req.(*GetUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UrcAuthApi_GetProviderUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProviderUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UrcAuthApiServer).GetProviderUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UrcAuthApi_GetProviderUserId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UrcAuthApiServer).GetProviderUserId(ctx, req.(*GetProviderUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UrcAuthApi_ServiceDesc is the grpc.ServiceDesc for UrcAuthApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UrcAuthApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "epic_urc.UrcAuthApi",
	HandlerType: (*UrcAuthApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _UrcAuthApi_HealthCheck_Handler,
		},
		{
			MethodName: "StartAuthSession",
			Handler:    _UrcAuthApi_StartAuthSession_Handler,
		},
		{
			MethodName: "GetAuthSession",
			Handler:    _UrcAuthApi_GetAuthSession_Handler,
		},
		{
			MethodName: "RefreshAuthSession",
			Handler:    _UrcAuthApi_RefreshAuthSession_Handler,
		},
		{
			MethodName: "VerifyUser",
			Handler:    _UrcAuthApi_VerifyUser_Handler,
		},
		{
			MethodName: "ExchangeExternalTokenForUserToken",
			Handler:    _UrcAuthApi_ExchangeExternalTokenForUserToken_Handler,
		},
		{
			MethodName: "ExchangeAPIKeyForUserToken",
			Handler:    _UrcAuthApi_ExchangeAPIKeyForUserToken_Handler,
		},
		{
			MethodName: "ExchangeUserTokenForMultiresourceToken",
			Handler:    _UrcAuthApi_ExchangeUserTokenForMultiresourceToken_Handler,
		},
		{
			MethodName: "CheckUserPermission",
			Handler:    _UrcAuthApi_CheckUserPermission_Handler,
		},
		{
			MethodName: "LookupUserPermissions",
			Handler:    _UrcAuthApi_LookupUserPermissions_Handler,
		},
		{
			MethodName: "GetUserInfo",
			Handler:    _UrcAuthApi_GetUserInfo_Handler,
		},
		{
			MethodName: "GetUserId",
			Handler:    _UrcAuthApi_GetUserId_Handler,
		},
		{
			MethodName: "GetProviderUserId",
			Handler:    _UrcAuthApi_GetProviderUserId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "epicurc/auth_api.proto",
}
