// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ucsauth/rebac_api.proto

package ucsauth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceName  string                 `protobuf:"bytes,2,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourceRequest) Reset() {
	*x = CreateResourceRequest{}
	mi := &file_ucsauth_rebac_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceRequest) ProtoMessage() {}

func (x *CreateResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ucsauth_rebac_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceRequest.ProtoReflect.Descriptor instead.
func (*CreateResourceRequest) Descriptor() ([]byte, []int) {
	return file_ucsauth_rebac_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateResourceRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *CreateResourceRequest) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

type CreateResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourceResponse) Reset() {
	*x = CreateResourceResponse{}
	mi := &file_ucsauth_rebac_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceResponse) ProtoMessage() {}

func (x *CreateResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ucsauth_rebac_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceResponse.ProtoReflect.Descriptor instead.
func (*CreateResourceResponse) Descriptor() ([]byte, []int) {
	return file_ucsauth_rebac_api_proto_rawDescGZIP(), []int{1}
}

type DeleteResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceRequest) Reset() {
	*x = DeleteResourceRequest{}
	mi := &file_ucsauth_rebac_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceRequest) ProtoMessage() {}

func (x *DeleteResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ucsauth_rebac_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceRequest.ProtoReflect.Descriptor instead.
func (*DeleteResourceRequest) Descriptor() ([]byte, []int) {
	return file_ucsauth_rebac_api_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteResourceRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type DeleteResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceResponse) Reset() {
	*x = DeleteResourceResponse{}
	mi := &file_ucsauth_rebac_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceResponse) ProtoMessage() {}

func (x *DeleteResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ucsauth_rebac_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceResponse.ProtoReflect.Descriptor instead.
func (*DeleteResourceResponse) Descriptor() ([]byte, []int) {
	return file_ucsauth_rebac_api_proto_rawDescGZIP(), []int{3}
}

var File_ucsauth_rebac_api_proto protoreflect.FileDescriptor

const file_ucsauth_rebac_api_proto_rawDesc = "" +
	"\n" +
	"\x17ucsauth/rebac_api.proto\x12\bucs.auth\"]\n" +
	"\x15CreateResourceRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12#\n" +
	"\rresource_name\x18\x02 \x01(\tR\fresourceName\"\x18\n" +
	"\x16CreateResourceResponse\"8\n" +
	"\x15DeleteResourceRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\"\x18\n" +
	"\x16DeleteResourceResponse2\xb8\x01\n" +
	"\bRebacApi\x12U\n" +
	"\x0eCreateResource\x12\x1f.ucs.auth.CreateResourceRequest\x1a .ucs.auth.CreateResourceResponse\"\x00\x12U\n" +
	"\x0eDeleteResource\x12\x1f.ucs.auth.DeleteResourceRequest\x1a .ucs.auth.DeleteResourceResponse\"\x00BLZJgithub.com/yamahigashi/lore-auth-bridge/internal/loreproto/ucsauth;ucsauthb\x06proto3"

var (
	file_ucsauth_rebac_api_proto_rawDescOnce sync.Once
	file_ucsauth_rebac_api_proto_rawDescData []byte
)

func file_ucsauth_rebac_api_proto_rawDescGZIP() []byte {
	file_ucsauth_rebac_api_proto_rawDescOnce.Do(func() {
		file_ucsauth_rebac_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ucsauth_rebac_api_proto_rawDesc), len(file_ucsauth_rebac_api_proto_rawDesc)))
	})
	return file_ucsauth_rebac_api_proto_rawDescData
}

var file_ucsauth_rebac_api_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ucsauth_rebac_api_proto_goTypes = []any{
	(*CreateResourceRequest)(nil),  // 0: ucs.auth.CreateResourceRequest
	(*CreateResourceResponse)(nil), // 1: ucs.auth.CreateResourceResponse
	(*DeleteResourceRequest)(nil),  // 2: ucs.auth.DeleteResourceRequest
	(*DeleteResourceResponse)(nil), // 3: ucs.auth.DeleteResourceResponse
}
var file_ucsauth_rebac_api_proto_depIdxs = []int32{
	0, // 0: ucs.auth.RebacApi.CreateResource:input_type -> ucs.auth.CreateResourceRequest
	2, // 1: ucs.auth.RebacApi.DeleteResource:input_type -> ucs.auth.DeleteResourceRequest
	1, // 2: ucs.auth.RebacApi.CreateResource:output_type -> ucs.auth.CreateResourceResponse
	3, // 3: ucs.auth.RebacApi.DeleteResource:output_type -> ucs.auth.DeleteResourceResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ucsauth_rebac_api_proto_init() }
func file_ucsauth_rebac_api_proto_init() {
	if File_ucsauth_rebac_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ucsauth_rebac_api_proto_rawDesc), len(file_ucsauth_rebac_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ucsauth_rebac_api_proto_goTypes,
		DependencyIndexes: file_ucsauth_rebac_api_proto_depIdxs,
		MessageInfos:      file_ucsauth_rebac_api_proto_msgTypes,
	}.Build()
	File_ucsauth_rebac_api_proto = out.File
	file_ucsauth_rebac_api_proto_goTypes = nil
	file_ucsauth_rebac_api_proto_depIdxs = nil
}
