// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: epicurc/auth_api.proto

package epicurc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TargetUser struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to User:
	//
	//	*TargetUser_UserToken
	User          isTargetUser_User `protobuf_oneof:"user"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetUser) Reset() {
	*x = TargetUser{}
	mi := &file_epicurc_auth_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetUser) ProtoMessage() {}

func (x *TargetUser) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetUser.ProtoReflect.Descriptor instead.
func (*TargetUser) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{0}
}

func (x *TargetUser) GetUser() isTargetUser_User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *TargetUser) GetUserToken() string {
	if x != nil {
		if x, ok := x.User.(*TargetUser_UserToken); ok {
			return x.UserToken
		}
	}
	return ""
}

type isTargetUser_User interface {
	isTargetUser_User()
}

type TargetUser_UserToken struct {
	UserToken string `protobuf:"bytes,1,opt,name=user_token,json=userToken,proto3,oneof"`
}

func (*TargetUser_UserToken) isTargetUser_User() {}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_epicurc_auth_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{1}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_epicurc_auth_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{2}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StartAuthSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientState   string                 `protobuf:"bytes,1,opt,name=client_state,json=clientState,proto3" json:"client_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAuthSessionRequest) Reset() {
	*x = StartAuthSessionRequest{}
	mi := &file_epicurc_auth_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAuthSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAuthSessionRequest) ProtoMessage() {}

func (x *StartAuthSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAuthSessionRequest.ProtoReflect.Descriptor instead.
func (*StartAuthSessionRequest) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{3}
}

func (x *StartAuthSessionRequest) GetClientState() string {
	if x != nil {
		return x.ClientState
	}
	return ""
}

type StartAuthSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionCode   string                 `protobuf:"bytes,1,opt,name=session_code,json=sessionCode,proto3" json:"session_code,omitempty"`
	LoginUrl      string                 `protobuf:"bytes,2,opt,name=login_url,json=loginUrl,proto3" json:"login_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAuthSessionResponse) Reset() {
	*x = StartAuthSessionResponse{}
	mi := &file_epicurc_auth_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAuthSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAuthSessionResponse) ProtoMessage() {}

func (x *StartAuthSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAuthSessionResponse.ProtoReflect.Descriptor instead.
func (*StartAuthSessionResponse) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{4}
}

func (x *StartAuthSessionResponse) GetSessionCode() string {
	if x != nil {
		return x.SessionCode
	}
	return ""
}

func (x *StartAuthSessionResponse) GetLoginUrl() string {
	if x != nil {
		return x.LoginUrl
	}
	return ""
}

type GetAuthSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionCode   string                 `protobuf:"bytes,1,opt,name=session_code,json=sessionCode,proto3" json:"session_code,omitempty"`
	ClientState   string                 `protobuf:"bytes,2,opt,name=client_state,json=clientState,proto3" json:"client_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthSessionRequest) Reset() {
	*x = GetAuthSessionRequest{}
	mi := &file_epicurc_auth_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthSessionRequest) ProtoMessage() {}

func (x *GetAuthSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthSessionRequest.ProtoReflect.Descriptor instead.
func (*GetAuthSessionRequest) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetAuthSessionRequest) GetSessionCode() string {
	if x != nil {
		return x.SessionCode
	}
	return ""
}

func (x *GetAuthSessionRequest) GetClientState() string {
	if x != nil {
		return x.ClientState
	}
	return ""
}

type GetAuthSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserToken     *UserToken             `protobuf:"bytes,1,opt,name=user_token,json=userToken,proto3,oneof" json:"user_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthSessionResponse) Reset() {
	*x = GetAuthSessionResponse{}
	mi := &file_epicurc_auth_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthSessionResponse) ProtoMessage() {}

func (x *GetAuthSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthSessionResponse.ProtoReflect.Descriptor instead.
func (*GetAuthSessionResponse) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetAuthSessionResponse) GetUserToken() *UserToken {
	if x != nil {
		return x.UserToken
	}
	return nil
}

type RefreshAuthSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAuthSessionRequest) Reset() {
	*x = RefreshAuthSessionRequest{}
	mi := &file_epicurc_auth_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAuthSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAuthSessionRequest) ProtoMessage() {}

func (x *RefreshAuthSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAuthSessionRequest.ProtoReflect.Descriptor instead.
func (*RefreshAuthSessionRequest) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{7}
}

type RefreshAuthSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserToken     *UserToken             `protobuf:"bytes,1,opt,name=user_token,json=userToken,proto3,oneof" json:"user_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAuthSessionResponse) Reset() {
	*x = RefreshAuthSessionResponse{}
	mi := &file_epicurc_auth_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAuthSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAuthSessionResponse) ProtoMessage() {}

func (x *RefreshAuthSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAuthSessionResponse.ProtoReflect.Descriptor instead.
func (*RefreshAuthSessionResponse) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{8}
}

func (x *RefreshAuthSessionResponse) GetUserToken() *UserToken {
	if x != nil {
		return x.UserToken
	}
	return nil
}

// Verify the target is compliant with the given Product Name as registered in `ucs-auth-api` config
type VerifyCompliance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductName   string                 `protobuf:"bytes,1,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCompliance) Reset() {
	*x = VerifyCompliance{}
	mi := &file_epicurc_auth_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCompliance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCompliance) ProtoMessage() {}

func (x *VerifyCompliance) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCompliance.ProtoReflect.Descriptor instead.
func (*VerifyCompliance) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyCompliance) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

type VerifyRequirement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Requirement:
	//
	//	*VerifyRequirement_Compliance
	Requirement   isVerifyRequirement_Requirement `protobuf_oneof:"requirement"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequirement) Reset() {
	*x = VerifyRequirement{}
	mi := &file_epicurc_auth_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequirement) ProtoMessage() {}

func (x *VerifyRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequirement.ProtoReflect.Descriptor instead.
func (*VerifyRequirement) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyRequirement) GetRequirement() isVerifyRequirement_Requirement {
	if x != nil {
		return x.Requirement
	}
	return nil
}

func (x *VerifyRequirement) GetCompliance() *VerifyCompliance {
	if x != nil {
		if x, ok := x.Requirement.(*VerifyRequirement_Compliance); ok {
			return x.Compliance
		}
	}
	return nil
}

type isVerifyRequirement_Requirement interface {
	isVerifyRequirement_Requirement()
}

type VerifyRequirement_Compliance struct {
	Compliance *VerifyCompliance `protobuf:"bytes,2,opt,name=compliance,proto3,oneof"`
}

func (*VerifyRequirement_Compliance) isVerifyRequirement_Requirement() {}

type VerifyUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUser    *TargetUser            `protobuf:"bytes,1,opt,name=target_user,json=targetUser,proto3" json:"target_user,omitempty"`
	Requirements  []*VerifyRequirement   `protobuf:"bytes,2,rep,name=requirements,proto3" json:"requirements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyUserRequest) Reset() {
	*x = VerifyUserRequest{}
	mi := &file_epicurc_auth_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyUserRequest) ProtoMessage() {}

func (x *VerifyUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyUserRequest.ProtoReflect.Descriptor instead.
func (*VerifyUserRequest) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{11}
}

func (x *VerifyUserRequest) GetTargetUser() *TargetUser {
	if x != nil {
		return x.TargetUser
	}
	return nil
}

func (x *VerifyUserRequest) GetRequirements() []*VerifyRequirement {
	if x != nil {
		return x.Requirements
	}
	return nil
}

type VerifyUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      *UserInfo              `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyUserResponse) Reset() {
	*x = VerifyUserResponse{}
	mi := &file_epicurc_auth_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyUserResponse) ProtoMessage() {}

func (x *VerifyUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyUserResponse.ProtoReflect.Descriptor instead.
func (*VerifyUserResponse) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{12}
}

func (x *VerifyUserResponse) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type ExchangeExternalTokenForUserTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalToken string                 `protobuf:"bytes,1,opt,name=external_token,json=externalToken,proto3" json:"external_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeExternalTokenForUserTokenRequest) Reset() {
	*x = ExchangeExternalTokenForUserTokenRequest{}
	mi := &file_epicurc_auth_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeExternalTokenForUserTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeExternalTokenForUserTokenRequest) ProtoMessage() {}

func (x *ExchangeExternalTokenForUserTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeExternalTokenForUserTokenRequest.ProtoReflect.Descriptor instead.
func (*ExchangeExternalTokenForUserTokenRequest) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{13}
}

func (x *ExchangeExternalTokenForUserTokenRequest) GetExternalToken() string {
	if x != nil {
		return x.ExternalToken
	}
	return ""
}

func (x *ExchangeExternalTokenForUserTokenRequest) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

type ExchangeExternalTokenForUserTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserToken     *UserToken             `protobuf:"bytes,1,opt,name=user_token,json=userToken,proto3,oneof" json:"user_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeExternalTokenForUserTokenResponse) Reset() {
	*x = ExchangeExternalTokenForUserTokenResponse{}
	mi := &file_epicurc_auth_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeExternalTokenForUserTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeExternalTokenForUserTokenResponse) ProtoMessage() {}

func (x *ExchangeExternalTokenForUserTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeExternalTokenForUserTokenResponse.ProtoReflect.Descriptor instead.
func (*ExchangeExternalTokenForUserTokenResponse) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{14}
}

func (x *ExchangeExternalTokenForUserTokenResponse) GetUserToken() *UserToken {
	if x != nil {
		return x.UserToken
	}
	return nil
}

type ExchangeAPIKeyForUserTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeAPIKeyForUserTokenRequest) Reset() {
	*x = ExchangeAPIKeyForUserTokenRequest{}
	mi := &file_epicurc_auth_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeAPIKeyForUserTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeAPIKeyForUserTokenRequest) ProtoMessage() {}

func (x *ExchangeAPIKeyForUserTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeAPIKeyForUserTokenRequest.ProtoReflect.Descriptor instead.
func (*ExchangeAPIKeyForUserTokenRequest) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{15}
}

func (x *ExchangeAPIKeyForUserTokenRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type ExchangeAPIKeyForUserTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserToken     *UserToken             `protobuf:"bytes,1,opt,name=user_token,json=userToken,proto3,oneof" json:"user_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeAPIKeyForUserTokenResponse) Reset() {
	*x = ExchangeAPIKeyForUserTokenResponse{}
	mi := &file_epicurc_auth_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeAPIKeyForUserTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeAPIKeyForUserTokenResponse) ProtoMessage() {}

func (x *ExchangeAPIKeyForUserTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeAPIKeyForUserTokenResponse.ProtoReflect.Descriptor instead.
func (*ExchangeAPIKeyForUserTokenResponse) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{16}
}

func (x *ExchangeAPIKeyForUserTokenResponse) GetUserToken() *UserToken {
	if x != nil {
		return x.UserToken
	}
	return nil
}

type UserToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserToken     string                 `protobuf:"bytes,1,opt,name=user_token,json=userToken,proto3" json:"user_token,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Epoch
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`           // URC user ID
	UserName      string                 `protobuf:"bytes,4,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`     // Display name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserToken) Reset() {
	*x = UserToken{}
	mi := &file_epicurc_auth_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserToken) ProtoMessage() {}

func (x *UserToken) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserToken.ProtoReflect.Descriptor instead.
func (*UserToken) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{17}
}

func (x *UserToken) GetUserToken() string {
	if x != nil {
		return x.UserToken
	}
	return ""
}

func (x *UserToken) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *UserToken) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserToken) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type ResourcePermission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Permission    []string               `protobuf:"bytes,2,rep,name=permission,proto3" json:"permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourcePermission) Reset() {
	*x = ResourcePermission{}
	mi := &file_epicurc_auth_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourcePermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourcePermission) ProtoMessage() {}

func (x *ResourcePermission) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourcePermission.ProtoReflect.Descriptor instead.
func (*ResourcePermission) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{18}
}

func (x *ResourcePermission) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ResourcePermission) GetPermission() []string {
	if x != nil {
		return x.Permission
	}
	return nil
}

type ExchangeUserTokenForMultiresourceTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    []string               `protobuf:"bytes,1,rep,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeUserTokenForMultiresourceTokenRequest) Reset() {
	*x = ExchangeUserTokenForMultiresourceTokenRequest{}
	mi := &file_epicurc_auth_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeUserTokenForMultiresourceTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeUserTokenForMultiresourceTokenRequest) ProtoMessage() {}

func (x *ExchangeUserTokenForMultiresourceTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeUserTokenForMultiresourceTokenRequest.ProtoReflect.Descriptor instead.
func (*ExchangeUserTokenForMultiresourceTokenRequest) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{19}
}

func (x *ExchangeUserTokenForMultiresourceTokenRequest) GetResourceId() []string {
	if x != nil {
		return x.ResourceId
	}
	return nil
}

type ExchangeUserTokenForMultiresourceTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *UserToken             `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeUserTokenForMultiresourceTokenResponse) Reset() {
	*x = ExchangeUserTokenForMultiresourceTokenResponse{}
	mi := &file_epicurc_auth_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeUserTokenForMultiresourceTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeUserTokenForMultiresourceTokenResponse) ProtoMessage() {}

func (x *ExchangeUserTokenForMultiresourceTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeUserTokenForMultiresourceTokenResponse.ProtoReflect.Descriptor instead.
func (*ExchangeUserTokenForMultiresourceTokenResponse) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{20}
}

func (x *ExchangeUserTokenForMultiresourceTokenResponse) GetToken() *UserToken {
	if x != nil {
		return x.Token
	}
	return nil
}

type CheckUserPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    []string               `protobuf:"bytes,1,rep,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	TargetUser    *TargetUser            `protobuf:"bytes,2,opt,name=target_user,json=targetUser,proto3,oneof" json:"target_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserPermissionRequest) Reset() {
	*x = CheckUserPermissionRequest{}
	mi := &file_epicurc_auth_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserPermissionRequest) ProtoMessage() {}

func (x *CheckUserPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckUserPermissionRequest) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{21}
}

func (x *CheckUserPermissionRequest) GetResourceId() []string {
	if x != nil {
		return x.ResourceId
	}
	return nil
}

func (x *CheckUserPermissionRequest) GetTargetUser() *TargetUser {
	if x != nil {
		return x.TargetUser
	}
	return nil
}

type CheckUserPermissionResponse struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	AllowedResourcePermission []*ResourcePermission  `protobuf:"bytes,1,rep,name=allowed_resource_permission,json=allowedResourcePermission,proto3" json:"allowed_resource_permission,omitempty"`
	DeniedResourcePermission  []*ResourcePermission  `protobuf:"bytes,2,rep,name=denied_resource_permission,json=deniedResourcePermission,proto3" json:"denied_resource_permission,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *CheckUserPermissionResponse) Reset() {
	*x = CheckUserPermissionResponse{}
	mi := &file_epicurc_auth_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserPermissionResponse) ProtoMessage() {}

func (x *CheckUserPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserPermissionResponse.ProtoReflect.Descriptor instead.
func (*CheckUserPermissionResponse) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{22}
}

func (x *CheckUserPermissionResponse) GetAllowedResourcePermission() []*ResourcePermission {
	if x != nil {
		return x.AllowedResourcePermission
	}
	return nil
}

func (x *CheckUserPermissionResponse) GetDeniedResourcePermission() []*ResourcePermission {
	if x != nil {
		return x.DeniedResourcePermission
	}
	return nil
}

type LookupUserPermissionsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResourceFilter string                 `protobuf:"bytes,1,opt,name=resource_filter,json=resourceFilter,proto3" json:"resource_filter,omitempty"`
	ContextFilter  *string                `protobuf:"bytes,2,opt,name=context_filter,json=contextFilter,proto3,oneof" json:"context_filter,omitempty"`
	PageSize       *int32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	PageToken      *string                `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LookupUserPermissionsRequest) Reset() {
	*x = LookupUserPermissionsRequest{}
	mi := &file_epicurc_auth_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupUserPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupUserPermissionsRequest) ProtoMessage() {}

func (x *LookupUserPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupUserPermissionsRequest.ProtoReflect.Descriptor instead.
func (*LookupUserPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{23}
}

func (x *LookupUserPermissionsRequest) GetResourceFilter() string {
	if x != nil {
		return x.ResourceFilter
	}
	return ""
}

func (x *LookupUserPermissionsRequest) GetContextFilter() string {
	if x != nil && x.ContextFilter != nil {
		return *x.ContextFilter
	}
	return ""
}

func (x *LookupUserPermissionsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *LookupUserPermissionsRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type LookupUserPermissionsResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ResourcePermission []*ResourcePermission  `protobuf:"bytes,1,rep,name=resource_permission,json=resourcePermission,proto3" json:"resource_permission,omitempty"`
	NextPageToken      *string                `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3,oneof" json:"next_page_token,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LookupUserPermissionsResponse) Reset() {
	*x = LookupUserPermissionsResponse{}
	mi := &file_epicurc_auth_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupUserPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupUserPermissionsResponse) ProtoMessage() {}

func (x *LookupUserPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupUserPermissionsResponse.ProtoReflect.Descriptor instead.
func (*LookupUserPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{24}
}

func (x *LookupUserPermissionsResponse) GetResourcePermission() []*ResourcePermission {
	if x != nil {
		return x.ResourcePermission
	}
	return nil
}

func (x *LookupUserPermissionsResponse) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	UserId        []string               `protobuf:"bytes,2,rep,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_epicurc_auth_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{25}
}

func (x *GetUserInfoRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *GetUserInfoRequest) GetUserId() []string {
	if x != nil {
		return x.UserId
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_epicurc_auth_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{26}
}

func (x *UserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type GetUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      []*UserInfo            `protobuf:"bytes,1,rep,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_epicurc_auth_api_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{27}
}

func (x *GetUserInfoResponse) GetUserInfo() []*UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type GetUserIdRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ResourceId      string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	UserDisplayName string                 `protobuf:"bytes,2,opt,name=user_display_name,json=userDisplayName,proto3" json:"user_display_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUserIdRequest) Reset() {
	*x = GetUserIdRequest{}
	mi := &file_epicurc_auth_api_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserIdRequest) ProtoMessage() {}

func (x *GetUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserIdRequest) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{28}
}

func (x *GetUserIdRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *GetUserIdRequest) GetUserDisplayName() string {
	if x != nil {
		return x.UserDisplayName
	}
	return ""
}

type GetUserIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      *UserInfo              `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserIdResponse) Reset() {
	*x = GetUserIdResponse{}
	mi := &file_epicurc_auth_api_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserIdResponse) ProtoMessage() {}

func (x *GetUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserIdResponse.ProtoReflect.Descriptor instead.
func (*GetUserIdResponse) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{29}
}

func (x *GetUserIdResponse) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type GetProviderUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderUserIdRequest) Reset() {
	*x = GetProviderUserIdRequest{}
	mi := &file_epicurc_auth_api_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderUserIdRequest) ProtoMessage() {}

func (x *GetProviderUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetProviderUserIdRequest) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{30}
}

func (x *GetProviderUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetProviderUserIdResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProviderUserId string                 `protobuf:"bytes,2,opt,name=provider_user_id,json=providerUserId,proto3" json:"provider_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetProviderUserIdResponse) Reset() {
	*x = GetProviderUserIdResponse{}
	mi := &file_epicurc_auth_api_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderUserIdResponse) ProtoMessage() {}

func (x *GetProviderUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_epicurc_auth_api_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderUserIdResponse.ProtoReflect.Descriptor instead.
func (*GetProviderUserIdResponse) Descriptor() ([]byte, []int) {
	return file_epicurc_auth_api_proto_rawDescGZIP(), []int{31}
}

func (x *GetProviderUserIdResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetProviderUserIdResponse) GetProviderUserId() string {
	if x != nil {
		return x.ProviderUserId
	}
	return ""
}

var File_epicurc_auth_api_proto protoreflect.FileDescriptor

const file_epicurc_auth_api_proto_rawDesc = "" +
	"\n" +
	"\x16epicurc/auth_api.proto\x12\bepic_urc\"5\n" +
	"\n" +
	"TargetUser\x12\x1f\n" +
	"\n" +
	"user_token\x18\x01 \x01(\tH\x00R\tuserTokenB\x06\n" +
	"\x04user\"\x14\n" +
	"\x12HealthCheckRequest\"-\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"<\n" +
	"\x17StartAuthSessionRequest\x12!\n" +
	"\fclient_state\x18\x01 \x01(\tR\vclientState\"Z\n" +
	"\x18StartAuthSessionResponse\x12!\n" +
	"\fsession_code\x18\x01 \x01(\tR\vsessionCode\x12\x1b\n" +
	"\tlogin_url\x18\x02 \x01(\tR\bloginUrl\"]\n" +
	"\x15GetAuthSessionRequest\x12!\n" +
	"\fsession_code\x18\x01 \x01(\tR\vsessionCode\x12!\n" +
	"\fclient_state\x18\x02 \x01(\tR\vclientState\"`\n" +
	"\x16GetAuthSessionResponse\x127\n" +
	"\n" +
	"user_token\x18\x01 \x01(\v2\x13.epic_urc.UserTokenH\x00R\tuserToken\x88\x01\x01B\r\n" +
	"\v_user_token\"\x1b\n" +
	"\x19RefreshAuthSessionRequest\"d\n" +
	"\x1aRefreshAuthSessionResponse\x127\n" +
	"\n" +
	"user_token\x18\x01 \x01(\v2\x13.epic_urc.UserTokenH\x00R\tuserToken\x88\x01\x01B\r\n" +
	"\v_user_token\"5\n" +
	"\x10VerifyCompliance\x12!\n" +
	"\fproduct_name\x18\x01 \x01(\tR\vproductName\"f\n" +
	"\x11VerifyRequirement\x12<\n" +
	"\n" +
	"compliance\x18\x02 \x01(\v2\x1a.epic_urc.VerifyComplianceH\x00R\n" +
	"complianceB\r\n" +
	"\vrequirementJ\x04\b\x01\x10\x02\"\x8b\x01\n" +
	"\x11VerifyUserRequest\x125\n" +
	"\vtarget_user\x18\x01 \x01(\v2\x14.epic_urc.TargetUserR\n" +
	"targetUser\x12?\n" +
	"\frequirements\x18\x02 \x03(\v2\x1b.epic_urc.VerifyRequirementR\frequirements\"E\n" +
	"\x12VerifyUserResponse\x12/\n" +
	"\tuser_info\x18\x01 \x01(\v2\x12.epic_urc.UserInfoR\buserInfo\"p\n" +
	"(ExchangeExternalTokenForUserTokenRequest\x12%\n" +
	"\x0eexternal_token\x18\x01 \x01(\tR\rexternalToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\"s\n" +
	")ExchangeExternalTokenForUserTokenResponse\x127\n" +
	"\n" +
	"user_token\x18\x01 \x01(\v2\x13.epic_urc.UserTokenH\x00R\tuserToken\x88\x01\x01B\r\n" +
	"\v_user_token\"<\n" +
	"!ExchangeAPIKeyForUserTokenRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\"l\n" +
	"\"ExchangeAPIKeyForUserTokenResponse\x127\n" +
	"\n" +
	"user_token\x18\x01 \x01(\v2\x13.epic_urc.UserTokenH\x00R\tuserToken\x88\x01\x01B\r\n" +
	"\v_user_token\"\x7f\n" +
	"\tUserToken\x12\x1d\n" +
	"\n" +
	"user_token\x18\x01 \x01(\tR\tuserToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x04 \x01(\tR\buserName\"U\n" +
	"\x12ResourcePermission\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x1e\n" +
	"\n" +
	"permission\x18\x02 \x03(\tR\n" +
	"permission\"P\n" +
	"-ExchangeUserTokenForMultiresourceTokenRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x03(\tR\n" +
	"resourceId\"[\n" +
	".ExchangeUserTokenForMultiresourceTokenResponse\x12)\n" +
	"\x05token\x18\x01 \x01(\v2\x13.epic_urc.UserTokenR\x05token\"\x89\x01\n" +
	"\x1aCheckUserPermissionRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x03(\tR\n" +
	"resourceId\x12:\n" +
	"\vtarget_user\x18\x02 \x01(\v2\x14.epic_urc.TargetUserH\x00R\n" +
	"targetUser\x88\x01\x01B\x0e\n" +
	"\f_target_user\"\xd7\x01\n" +
	"\x1bCheckUserPermissionResponse\x12\\\n" +
	"\x1ballowed_resource_permission\x18\x01 \x03(\v2\x1c.epic_urc.ResourcePermissionR\x19allowedResourcePermission\x12Z\n" +
	"\x1adenied_resource_permission\x18\x02 \x03(\v2\x1c.epic_urc.ResourcePermissionR\x18deniedResourcePermission\"\xe9\x01\n" +
	"\x1cLookupUserPermissionsRequest\x12'\n" +
	"\x0fresource_filter\x18\x01 \x01(\tR\x0eresourceFilter\x12*\n" +
	"\x0econtext_filter\x18\x02 \x01(\tH\x00R\rcontextFilter\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x03 \x01(\x05H\x01R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tH\x02R\tpageToken\x88\x01\x01B\x11\n" +
	"\x0f_context_filterB\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_token\"\xaf\x01\n" +
	"\x1dLookupUserPermissionsResponse\x12M\n" +
	"\x13resource_permission\x18\x01 \x03(\v2\x1c.epic_urc.ResourcePermissionR\x12resourcePermission\x12+\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tH\x00R\rnextPageToken\x88\x01\x01B\x12\n" +
	"\x10_next_page_token\"N\n" +
	"\x12GetUserInfoRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x17\n" +
	"\auser_id\x18\x02 \x03(\tR\x06userId\"F\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"F\n" +
	"\x13GetUserInfoResponse\x12/\n" +
	"\tuser_info\x18\x01 \x03(\v2\x12.epic_urc.UserInfoR\buserInfo\"_\n" +
	"\x10GetUserIdRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12*\n" +
	"\x11user_display_name\x18\x02 \x01(\tR\x0fuserDisplayName\"D\n" +
	"\x11GetUserIdResponse\x12/\n" +
	"\tuser_info\x18\x01 \x01(\v2\x12.epic_urc.UserInfoR\buserInfo\"3\n" +
	"\x18GetProviderUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"^\n" +
	"\x19GetProviderUserIdResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12(\n" +
	"\x10provider_user_id\x18\x02 \x01(\tR\x0eproviderUserId2\xb0\n" +
	"\n" +
	"\n" +
	"UrcAuthApi\x12L\n" +
	"\vHealthCheck\x12\x1c.epic_urc.HealthCheckRequest\x1a\x1d.epic_urc.HealthCheckResponse\"\x00\x12[\n" +
	"\x10StartAuthSession\x12!.epic_urc.StartAuthSessionRequest\x1a\".epic_urc.StartAuthSessionResponse\"\x00\x12U\n" +
	"\x0eGetAuthSession\x12\x1f.epic_urc.GetAuthSessionRequest\x1a .epic_urc.GetAuthSessionResponse\"\x00\x12a\n" +
	"\x12RefreshAuthSession\x12#.epic_urc.RefreshAuthSessionRequest\x1a$.epic_urc.RefreshAuthSessionResponse\"\x00\x12I\n" +
	"\n" +
	"VerifyUser\x12\x1b.epic_urc.VerifyUserRequest\x1a\x1c.epic_urc.VerifyUserResponse\"\x00\x12\x8e\x01\n" +
	"!ExchangeExternalTokenForUserToken\x122.epic_urc.ExchangeExternalTokenForUserTokenRequest\x1a3.epic_urc.ExchangeExternalTokenForUserTokenResponse\"\x00\x12y\n" +
	"\x1aExchangeAPIKeyForUserToken\x12+.epic_urc.ExchangeAPIKeyForUserTokenRequest\x1a,.epic_urc.ExchangeAPIKeyForUserTokenResponse\"\x00\x12\x9d\x01\n" +
	"&ExchangeUserTokenForMultiresourceToken\x127.epic_urc.ExchangeUserTokenForMultiresourceTokenRequest\x1a8.epic_urc.ExchangeUserTokenForMultiresourceTokenResponse\"\x00\x12d\n" +
	"\x13CheckUserPermission\x12$.epic_urc.CheckUserPermissionRequest\x1a%.epic_urc.CheckUserPermissionResponse\"\x00\x12j\n" +
	"\x15LookupUserPermissions\x12&.epic_urc.LookupUserPermissionsRequest\x1a'.epic_urc.LookupUserPermissionsResponse\"\x00\x12L\n" +
	"\vGetUserInfo\x12\x1c.epic_urc.GetUserInfoRequest\x1a\x1d.epic_urc.GetUserInfoResponse\"\x00\x12F\n" +
	"\tGetUserId\x12\x1a.epic_urc.GetUserIdRequest\x1a\x1b.epic_urc.GetUserIdResponse\"\x00\x12^\n" +
	"\x11GetProviderUserId\x12\".epic_urc.GetProviderUserIdRequest\x1a#.epic_urc.GetProviderUserIdResponse\"\x00BLZJgithub.com/yamahigashi/lore-auth-bridge/internal/loreproto/epicurc;epicurcb\x06proto3"

var (
	file_epicurc_auth_api_proto_rawDescOnce sync.Once
	file_epicurc_auth_api_proto_rawDescData []byte
)

func file_epicurc_auth_api_proto_rawDescGZIP() []byte {
	file_epicurc_auth_api_proto_rawDescOnce.Do(func() {
		file_epicurc_auth_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_epicurc_auth_api_proto_rawDesc), len(file_epicurc_auth_api_proto_rawDesc)))
	})
	return file_epicurc_auth_api_proto_rawDescData
}

var file_epicurc_auth_api_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_epicurc_auth_api_proto_goTypes = []any{
	(*TargetUser)(nil),                                     // 0: epic_urc.TargetUser
	(*HealthCheckRequest)(nil),                             // 1: epic_urc.HealthCheckRequest
	(*HealthCheckResponse)(nil),                            // 2: epic_urc.HealthCheckResponse
	(*StartAuthSessionRequest)(nil),                        // 3: epic_urc.StartAuthSessionRequest
	(*StartAuthSessionResponse)(nil),                       // 4: epic_urc.StartAuthSessionResponse
	(*GetAuthSessionRequest)(nil),                          // 5: epic_urc.GetAuthSessionRequest
	(*GetAuthSessionResponse)(nil),                         // 6: epic_urc.GetAuthSessionResponse
	(*RefreshAuthSessionRequest)(nil),                      // 7: epic_urc.RefreshAuthSessionRequest
	(*RefreshAuthSessionResponse)(nil),                     // 8: epic_urc.RefreshAuthSessionResponse
	(*VerifyCompliance)(nil),                               // 9: epic_urc.VerifyCompliance
	(*VerifyRequirement)(nil),                              // 10: epic_urc.VerifyRequirement
	(*VerifyUserRequest)(nil),                              // 11: epic_urc.VerifyUserRequest
	(*VerifyUserResponse)(nil),                             // 12: epic_urc.VerifyUserResponse
	(*ExchangeExternalTokenForUserTokenRequest)(nil),       // 13: epic_urc.ExchangeExternalTokenForUserTokenRequest
	(*ExchangeExternalTokenForUserTokenResponse)(nil),      // 14: epic_urc.ExchangeExternalTokenForUserTokenResponse
	(*ExchangeAPIKeyForUserTokenRequest)(nil),              // 15: epic_urc.ExchangeAPIKeyForUserTokenRequest
	(*ExchangeAPIKeyForUserTokenResponse)(nil),             // 16: epic_urc.ExchangeAPIKeyForUserTokenResponse
	(*UserToken)(nil),                                      // 17: epic_urc.UserToken
	(*ResourcePermission)(nil),                             // 18: epic_urc.ResourcePermission
	(*ExchangeUserTokenForMultiresourceTokenRequest)(nil),  // 19: epic_urc.ExchangeUserTokenForMultiresourceTokenRequest
	(*ExchangeUserTokenForMultiresourceTokenResponse)(nil), // 20: epic_urc.ExchangeUserTokenForMultiresourceTokenResponse
	(*CheckUserPermissionRequest)(nil),                     // 21: epic_urc.CheckUserPermissionRequest
	(*CheckUserPermissionResponse)(nil),                    // 22: epic_urc.CheckUserPermissionResponse
	(*LookupUserPermissionsRequest)(nil),                   // 23: epic_urc.LookupUserPermissionsRequest
	(*LookupUserPermissionsResponse)(nil),                  // 24: epic_urc.LookupUserPermissionsResponse
	(*GetUserInfoRequest)(nil),                             // 25: epic_urc.GetUserInfoRequest
	(*UserInfo)(nil),                                       // 26: epic_urc.UserInfo
	(*GetUserInfoResponse)(nil),                            // 27: epic_urc.GetUserInfoResponse
	(*GetUserIdRequest)(nil),                               // 28: epic_urc.GetUserIdRequest
	(*GetUserIdResponse)(nil),                              // 29: epic_urc.GetUserIdResponse
	(*GetProviderUserIdRequest)(nil),                       // 30: epic_urc.GetProviderUserIdRequest
	(*GetProviderUserIdResponse)(nil),                      // 31: epic_urc.GetProviderUserIdResponse
}
var file_epicurc_auth_api_proto_depIdxs = []int32{
	17, // 0: epic_urc.GetAuthSessionResponse.user_token:type_name -> epic_urc.UserToken
	17, // 1: epic_urc.RefreshAuthSessionResponse.user_token:type_name -> epic_urc.UserToken
	9,  // 2: epic_urc.VerifyRequirement.compliance:type_name -> epic_urc.VerifyCompliance
	0,  // 3: epic_urc.VerifyUserRequest.target_user:type_name -> epic_urc.TargetUser
	10, // 4: epic_urc.VerifyUserRequest.requirements:type_name -> epic_urc.VerifyRequirement
	26, // 5: epic_urc.VerifyUserResponse.user_info:type_name -> epic_urc.UserInfo
	17, // 6: epic_urc.ExchangeExternalTokenForUserTokenResponse.user_token:type_name -> epic_urc.UserToken
	17, // 7: epic_urc.ExchangeAPIKeyForUserTokenResponse.user_token:type_name -> epic_urc.UserToken
	17, // 8: epic_urc.ExchangeUserTokenForMultiresourceTokenResponse.token:type_name -> epic_urc.UserToken
	0,  // 9: epic_urc.CheckUserPermissionRequest.target_user:type_name -> epic_urc.TargetUser
	18, // 10: epic_urc.CheckUserPermissionResponse.allowed_resource_permission:type_name -> epic_urc.ResourcePermission
	18, // 11: epic_urc.CheckUserPermissionResponse.denied_resource_permission:type_name -> epic_urc.ResourcePermission
	18, // 12: epic_urc.LookupUserPermissionsResponse.resource_permission:type_name -> epic_urc.ResourcePermission
	26, // 13: epic_urc.GetUserInfoResponse.user_info:type_name -> epic_urc.UserInfo
	26, // 14: epic_urc.GetUserIdResponse.user_info:type_name -> epic_urc.UserInfo
	1,  // 15: epic_urc.UrcAuthApi.HealthCheck:input_type -> epic_urc.HealthCheckRequest
	3,  // 16: epic_urc.UrcAuthApi.StartAuthSession:input_type -> epic_urc.StartAuthSessionRequest
	5,  // 17: epic_urc.UrcAuthApi.GetAuthSession:input_type -> epic_urc.GetAuthSessionRequest
	7,  // 18: epic_urc.UrcAuthApi.RefreshAuthSession:input_type -> epic_urc.RefreshAuthSessionRequest
	11, // 19: epic_urc.UrcAuthApi.VerifyUser:input_type -> epic_urc.VerifyUserRequest
	13, // 20: epic_urc.UrcAuthApi.ExchangeExternalTokenForUserToken:input_type -> epic_urc.ExchangeExternalTokenForUserTokenRequest
	15, // 21: epic_urc.UrcAuthApi.ExchangeAPIKeyForUserToken:input_type -> epic_urc.ExchangeAPIKeyForUserTokenRequest
	19, // 22: epic_urc.UrcAuthApi.ExchangeUserTokenForMultiresourceToken:input_type -> epic_urc.ExchangeUserTokenForMultiresourceTokenRequest
	21, // 23: epic_urc.UrcAuthApi.CheckUserPermission:input_type -> epic_urc.CheckUserPermissionRequest
	23, // 24: epic_urc.UrcAuthApi.LookupUserPermissions:input_type -> epic_urc.LookupUserPermissionsRequest
	25, // 25: epic_urc.UrcAuthApi.GetUserInfo:input_type -> epic_urc.GetUserInfoRequest
	28, // 26: epic_urc.UrcAuthApi.GetUserId:input_type -> epic_urc.GetUserIdRequest
	30, // 27: epic_urc.UrcAuthApi.GetProviderUserId:input_type -> epic_urc.GetProviderUserIdRequest
	2,  // 28: epic_urc.UrcAuthApi.HealthCheck:output_type -> epic_urc.HealthCheckResponse
	4,  // 29: epic_urc.UrcAuthApi.StartAuthSession:output_type -> epic_urc.StartAuthSessionResponse
	6,  // 30: epic_urc.UrcAuthApi.GetAuthSession:output_type -> epic_urc.GetAuthSessionResponse
	8,  // 31: epic_urc.UrcAuthApi.RefreshAuthSession:output_type -> epic_urc.RefreshAuthSessionResponse
	12, // 32: epic_urc.UrcAuthApi.VerifyUser:output_type -> epic_urc.VerifyUserResponse
	14, // 33: epic_urc.UrcAuthApi.ExchangeExternalTokenForUserToken:output_type -> epic_urc.ExchangeExternalTokenForUserTokenResponse
	16, // 34: epic_urc.UrcAuthApi.ExchangeAPIKeyForUserToken:output_type -> epic_urc.ExchangeAPIKeyForUserTokenResponse
	20, // 35: epic_urc.UrcAuthApi.ExchangeUserTokenForMultiresourceToken:output_type -> epic_urc.ExchangeUserTokenForMultiresourceTokenResponse
	22, // 36: epic_urc.UrcAuthApi.CheckUserPermission:output_type -> epic_urc.CheckUserPermissionResponse
	24, // 37: epic_urc.UrcAuthApi.LookupUserPermissions:output_type -> epic_urc.LookupUserPermissionsResponse
	27, // 38: epic_urc.UrcAuthApi.GetUserInfo:output_type -> epic_urc.GetUserInfoResponse
	29, // 39: epic_urc.UrcAuthApi.GetUserId:output_type -> epic_urc.GetUserIdResponse
	31, // 40: epic_urc.UrcAuthApi.GetProviderUserId:output_type -> epic_urc.GetProviderUserIdResponse
	28, // [28:41] is the sub-list for method output_type
	15, // [15:28] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_epicurc_auth_api_proto_init() }
func file_epicurc_auth_api_proto_init() {
	if File_epicurc_auth_api_proto != nil {
		return
	}
	file_epicurc_auth_api_proto_msgTypes[0].OneofWrappers = []any{
		(*TargetUser_UserToken)(nil),
	}
	file_epicurc_auth_api_proto_msgTypes[6].OneofWrappers = []any{}
	file_epicurc_auth_api_proto_msgTypes[8].OneofWrappers = []any{}
	file_epicurc_auth_api_proto_msgTypes[10].OneofWrappers = []any{
		(*VerifyRequirement_Compliance)(nil),
	}
	file_epicurc_auth_api_proto_msgTypes[14].OneofWrappers = []any{}
	file_epicurc_auth_api_proto_msgTypes[16].OneofWrappers = []any{}
	file_epicurc_auth_api_proto_msgTypes[21].OneofWrappers = []any{}
	file_epicurc_auth_api_proto_msgTypes[23].OneofWrappers = []any{}
	file_epicurc_auth_api_proto_msgTypes[24].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_epicurc_auth_api_proto_rawDesc), len(file_epicurc_auth_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_epicurc_auth_api_proto_goTypes,
		DependencyIndexes: file_epicurc_auth_api_proto_depIdxs,
		MessageInfos:      file_epicurc_auth_api_proto_msgTypes,
	}.Build()
	File_epicurc_auth_api_proto = out.File
	file_epicurc_auth_api_proto_goTypes = nil
	file_epicurc_auth_api_proto_depIdxs = nil
}
